  const CARDS = {
    /* ===== TOKEN ===== */
    kage_token:  { kind:'ninja', name:'Schattendoppelgänger', level:1, atk:1000, def:1000, attr:'wind', emoji:'🍥', rarity:'N',
                   token:true, effect:null, desc:'Ein Doppelgänger aus reinem Chakra.' },

    /* ===== Füller (vanilla, Tests/Platzhalter) ===== */
    akademie_schueler: { kind:'ninja', name:'Akademie-Schüler', level:2, atk:1000, def:1000, attr:'erde', emoji:'🎓', rarity:'N',
                   effect:null, desc:'Ein Fleißiger aus der Ninja-Akademie — ohne besondere Jutsus.' },

    /* ===== STARTER-THEME: Team 7 / Konoha (tribe 'konoha') ===== */
    naruto_schueler: { kind:'ninja', name:'Naruto – Akademie-Schüler', level:3, atk:1300, def:800, attr:'wind', emoji:'🍥', rarity:'R', tribe:'konoha',
                   effect:{ t:'on_normal_search_jutsu' },
                   desc:'Wenn diese Karte NORMAL beschworen wird: Nimm 1 Jutsukarte aus deinem Deck auf die Hand.' },
    konohamaru_rivale: { kind:'ninja', name:'Konohamaru – Kleiner Rivale', level:2, atk:700, def:700, attr:'feuer', emoji:'🧒', rarity:'N', tribe:'konoha',
                   effect:{ t:'on_battle_destroy_summon', id:'naruto_genin' },
                   desc:'Wenn diese Karte durch KAMPF zerstört wird: Beschwöre 1 „Naruto – Genin" aus deinem Deck.' },
    naruto_genin: { kind:'ninja', name:'Naruto – Genin', level:4, atk:1500, def:1100, attr:'wind', emoji:'🍥', rarity:'R', tribe:'konoha',
                   effect:{ t:'aura_self_tribe', v:300, tribe:'konoha' },
                   desc:'Erhält +300 ANG, solange ein anderer Konoha-Ninja offen auf deiner Feldseite liegt.' },
    iruka_waechter: { kind:'ninja', name:'Iruka – Wachsamer Lehrer', level:4, atk:800, def:2200, attr:'wasser', emoji:'📚', rarity:'R', tribe:'konoha',
                   effects:[ { t:'no_direct' }, { t:'attack_redirect' } ],
                   desc:'Kann nicht direkt angreifen. Einmal pro Zug: Lenke das Ziel eines gegnerischen Angriffs auf diese Karte um.' },
    naruto_kyuubi: { kind:'ninja', name:'Naruto – Kyūbi-Modus', level:7, atk:2500, def:2000, attr:'finsternis', emoji:'🦊', rarity:'SR', tribe:'konoha', tribeTribute:'konoha',
                   effect:{ t:'destroy_weak_per_turn', maxAtk:2000 },
                   desc:'Tribut-Beschwörung: Erfordert 2 KONOHA-Ninja als Tribut. Einmal pro Zug: Wirf 1 Handkarte ab, um 1 gegnerisches Ninja mit höchstens 2000 ANG zu zerstören.' },
    team7_formation: { kind:'jutsu', sub:'normal', name:'Team 7 – Formation', emoji:'🤝', rarity:'SR',
                   effect:{ t:'sp_summon_hand_tribe', tribe:'konoha', drawIf:'naruto' },
                   desc:'Beschwöre 1 Konoha-Ninja aus deiner Hand als Spezialbeschwörung. Kontrollierst du einen Naruto: Ziehe 1 Karte.' },
    rasengan_genin: { kind:'jutsu', sub:'equip', name:'Rasengan (Genin)', emoji:'🌀', rarity:'R',
                   effect:{ t:'equip', atk:800, tribeId:'naruto_genin', burnOnKill:400 },
                   desc:'Ausrüstung nur für „Naruto – Genin": +800 ANG. Zerstört er ein Ninja durch Kampf: 400 Schaden für den Gegner.' },
    schattenspiel: { kind:'jutsu', sub:'dauer', name:'Schattenspiel', emoji:'🌫️', rarity:'SR',
                   effect:{ t:'cont_weaken_all', v:200, coinNegate:1 },
                   desc:'DAUER-KARTE: Alle gegnerischen Ninja verlieren 200 ANG/VERT. Greift eines an: Münzwurf — bei Kopf wird der Angriff abgebrochen.' },
    schatten_bindung: { kind:'jutsu', sub:'normal', name:'Schatten-Bindung', emoji:'🌑', rarity:'SR',
                   effect:{ t:'lock_monster', turns:2 },
                   desc:'1 gegnerisches Ninja kann 2 Züge lang weder angreifen noch seine Effekte nutzen.' },
    kawarimi_trick: { kind:'falle', trigger:'attack', name:'Kawarimi-Trick', emoji:'🪵', rarity:'N',
                   effect:{ t:'negate_attack_tribe', tribe:'konoha' },
                   desc:'FALLE: Wenn der Gegner angreift und du einen Konoha-Ninja kontrollierst: Annulliere den Angriff.' },
    schattentaeuschung: { kind:'falle', trigger:'summon', name:'Schattentäuschung', emoji:'🎭', rarity:'SR',
                   effect:{ t:'weaken_summoned', v:500, dmg:300 },
                   desc:'FALLE: Wenn der Gegner ein Ninja beschwört: Es verliert dauerhaft 500 ANG und der Gegner erhält 300 Schaden.' },

    /* ===== Kurogane Boss-Deck: Jiraiya & die Kröten (tribe 'kroete') ===== */
    jiraiya_eremit: { kind:'ninja', name:'Jiraiya – Der Reise-Eremit', level:3, atk:1200, def:1000, attr:'feuer', emoji:'🐸', rarity:'R',
                   effect:{ t:'on_normal_search_jutsu' },
                   desc:'Wenn diese Karte NORMAL beschworen wird: Nimm 1 Jutsukarte aus deinem Deck auf die Hand.' },
    gama:        { kind:'ninja', name:'Gama – Kleine Kröte', level:2, atk:600, def:800, attr:'wasser', emoji:'🐸', rarity:'N', tribe:'kroete',
                   effect:{ t:'on_battle_destroy_summon', id:'gamakichi_krieger' },
                   desc:'Wenn diese Karte durch KAMPF zerstört wird: Beschwöre 1 „Gamakichi – Tapferer Nachwuchs" aus deinem Deck.' },
    gamakichi_krieger: { kind:'ninja', name:'Gamakichi – Tapferer Nachwuchs', level:4, atk:1500, def:1200, attr:'wasser', emoji:'🐸', rarity:'R', tribe:'kroete',
                   effect:{ t:'aura_self_tribe', v:300, tribe:'kroete', idPrefix:'jiraiya' },
                   desc:'Erhält +300 ANG, solange ein anderer Jiraiya oder eine andere Kröte offen auf deiner Feldseite liegt.' },
    gamaken_waechter: { kind:'ninja', name:'Gamaken – Der Ungeschickte Beschwörer', level:4, atk:800, def:2200, attr:'wasser', emoji:'🐸', rarity:'R', tribe:'kroete',
                   effects:[ { t:'no_direct' }, { t:'attack_redirect' } ],
                   desc:'Kann nicht direkt angreifen. Einmal pro Zug: Lenke das Ziel eines gegnerischen Angriffs auf diese Karte um.' },
    gamabunta_koenig: { kind:'ninja', name:'Gamabunta – Kröten-König', level:7, atk:2400, def:2000, attr:'feuer', emoji:'🐸', rarity:'SR', tribe:'kroete', tribeTribute:'kroete',
                   effect:{ t:'bounce_enemy_per_turn' },
                   desc:'Tribut-Beschwörung: Erfordert 2 KRÖTEN als Tribut. Einmal pro Zug: Wirf 1 Handkarte ab, um 1 gegnerisches Ninja auf die Hand zurückzugeben.' },
    kroeten_ruf: { kind:'jutsu', sub:'normal', name:'Kuchiyose no Jutsu: Kröten-Ruf', emoji:'🐸', rarity:'SR',
                   effect:{ t:'sp_summon_hand_tribe', tribe:'kroete', drawIf:'jiraiya' },
                   desc:'Beschwöre 1 Kröte aus deiner Hand als Spezialbeschwörung. Kontrollierst du einen Jiraiya: Ziehe 1 Karte.' },
    rasengan_eremit: { kind:'jutsu', sub:'equip', name:'Rasengan (Eremit)', emoji:'🌀', rarity:'R',
                   effect:{ t:'equip', atk:800, tribeId:'jiraiya_eremit', burnOnKill:400 },
                   desc:'Ausrüstung nur für „Jiraiya – Der Reise-Eremit": +800 ANG. Zerstört er ein Ninja durch Kampf: 400 Schaden für den Gegner.' },
    yomi_numa:   { kind:'jutsu', sub:'dauer', name:'Sumpf der Unterwelt (Yomi Numa)', emoji:'🕳️', rarity:'SR',
                   effect:{ t:'cont_weaken_all', v:300, coinNegate:1 },
                   desc:'DAUER-KARTE: Alle gegnerischen Ninja verlieren 300 ANG/VERT. Greift eines an: Münzwurf — bei Kopf wird der Angriff abgebrochen.' },
    kroeten_magen: { kind:'jutsu', sub:'normal', name:'Ninjutsu-Rolle: Kröten-Magen', emoji:'📜', rarity:'SR',
                   effect:{ t:'lock_monster', turns:2 },
                   desc:'1 gegnerisches Ninja kann 2 Züge lang weder angreifen noch seine Effekte nutzen.' },
    kroeten_schild: { kind:'falle', trigger:'attack', name:'Kröten-Schild', emoji:'🛡️', rarity:'N',
                   effect:{ t:'negate_attack_tribe', tribe:'kroete', idPrefix:'jiraiya' },
                   desc:'FALLE: Wenn der Gegner angreift und du eine Kröte oder einen Jiraiya kontrollierst: Annulliere den Angriff.' },
    hartschaum:  { kind:'falle', trigger:'summon', name:'Kunst des Hartschaum-Haars (Ranjishioryū)', emoji:'🦁', rarity:'SR',
                   effect:{ t:'weaken_summoned', v:500, dmg:300 },
                   desc:'FALLE: Wenn der Gegner ein Ninja beschwört: Es verliert dauerhaft 500 ANG und der Gegner erhält 300 Schaden.' },
  };
