/* Generiert fehlende Kartenbilder per gemini-image-CLI in assets/cards/raw/<id>.png
   (nur IDs in der untigen Map, die noch kein JPG haben).
   Aufruf: node tools/genimg_missing.js [startIdx]  — idempotent, überspringt vorhandene. */
'use strict';
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const RAW = path.join(ROOT, 'assets', 'cards', 'raw');
const SERVER = path.join(require('os').homedir(), '.kimi-code', 'mcp', 'gemini-image', 'server.js');
const STYLE = ', plain anime screencap illustration, cel-shaded Naruto lineart, dramatic lighting, no card frame, no border, no text, no logo, no watermark';

const SUBJECTS = {
  /* --- Sand/Feuer/Kakashi/Aya-Füller --- */
  sandsturm: 'massive desert sandstorm engulfing a rocky battlefield',
  sand_mauer: 'wall of sand rising to block a kunai attack',
  kakashi_raikiri: 'silver-haired masked jonin with sharingan eye, lightning chakra crackling in his hand',
  sharingan_kopie: 'open ninja scroll with glowing copied jutsu symbols floating out',
  sharingan_konter: 'masked ninja copying an enemy fire jutsu with his sharingan, mirror effect',
  ninken_falle: 'pack of ninja dogs pouncing from ambush in a forest',
  aya_meisterin: 'confident trap-master kunoichi surrounded by wire traps and explosive tags',
  entschaerfen: 'kunoichi carefully cutting a trap wire with small scissors',
  chakra_reflexion: 'glowing blue chakra barrier deflecting an attack back to the attacker',
  wasserspiegel: 'giant water mirror wall reflecting charging ninja attackers',
  kunai_hagel: 'hail of kunai knives raining down from the sky',
  ketten_fesseln: 'ninja bound tightly in glowing chakra chains',
  schlangen_token: 'small white snake hatchling coiled with glowing purple eyes',
  schlangenbiss: 'giant snake biting down with venom dripping fangs',
  weisse_schlange: 'white snake coiling around an ancient scroll',
  schlangengrube: 'dark pit full of writhing snakes seen from above',
  mandas_zorn: 'giant purple snake rearing up angrily over a forest',
  kunai_sturm: 'storm of kunai knives flying in tight formation',
  jonin_reflex: 'jonin dodging shuriken leaving afterimages behind',
  kunai_falle: 'kunai trap triggered from a hidden tree branch mechanism',
  itachi_mangekyou: 'mangekyou sharingan eye close-up with crows flying across a dark red sky',
  genjutsu_spiegel: 'ninja trapped inside an illusion mirror world with shattered reflections',
  karasu_taeuschung: 'ninja body dissolving into a flock of black crows',
  /* --- Kagā-Corp (Story-OCs) --- */
  kagaa_wache: 'corporate ninja guard in navy uniform with earpiece, futuristic tower lobby',
  kagaa_techniker: 'ninja technician with goggles repairing a glowing chakra device',
  kagaa_analyst: 'ninja analyst with glasses studying holographic chakra charts',
  shizuka_protokoll: 'strict female officer ninja with a clipboard, navy corporate uniform',
  shizuka_kommandantin: 'commanding female ninja officer with an energy whip, corporate tower',
  corp_ruestung: 'high-tech chakra armor vest glowing with blue circuits',
  daten_analyse: 'floating holographic data screens with chakra readings',
  system_scan: 'blue scanning beam sweeping a dark room revealing hidden traps',
  neukalibrierung: 'glowing chakra orb being recalibrated inside a glass device',
  corp_sperrung: 'security barrier gate slamming shut with red warning lights',
  abwehr_protokoll: 'hexagonal energy shield deflecting an attack, corporate glow',
  kagaa_schildwache: 'heavy corporate guard ninja holding a large riot shield',
  raiga_scout: 'corporate scout ninja with binoculars on a skyscraper roof at dusk',
  kagaa_bollwerk: 'massive armored corporate ninja like a walking fortress',
  raiga_veteran: 'scarred corporate security chief with crossed arms, long trench coat',
  raiga_boss: 'elite corporate security commander with an impenetrable blue barrier aura, tower background',
  zugriff_verweigert: 'glowing red access-denied hologram blocking a ninja',
  sicherheits_sperre: 'tower security lockdown with heavy sealing gates closing',
  festnahme: 'ninja being arrested in glowing chakra handcuffs by corporate guards',
  tower_shield: 'translucent energy shield dome over a corporate tower',
  system_breach: 'hacker ninja breaking through digital firewalls, glitch effect',
  corp_falle: 'corporate trap portal banishing a ninja into darkness',
  eisener_vorhang: 'massive iron curtain wall slamming down onto a battlefield',
  archiv_kurator: 'robed archivist ninja with glowing scrolls in a vast dark archive',
  archiv_wache: 'armored archive guard holding a lantern in a dark hall',
  kagaa_direktor: 'elegant corporate director ninja in a white suit holding glowing echo energy, office',
  echo_relikt: 'ancient relic stone radiating dark echo energy on a pedestal',
  kagaa_boss: 'powerful corporate director with echo-archive aura, relics floating around him',
  archiv_zugriff: 'glowing archive terminal granting access, holographic key',
  verbotenes_relikt: 'dark forbidden relic with a skull shape glowing ominously',
  zeit_siegel: 'ancient time seal with clock gears and sealing script',
  archiv_duplikat: 'paper sheet duplicating into a shadowy clone inside an archive',
  echo_resonanz: 'resonating echo shockwave shattering glowing spell cards',
  archiv_siegel: 'sealing tag portal banishing a summoned ninja, archive hall',
  kagaa_autoritaet: 'commanding hand gesture stopping an attack mid-air, golden glow',
  /* --- Echo/Riss (Story-OCs, Kapitel 4) --- */
  monolith_splitter: 'small floating rock fragment with glowing runes',
  echo_waechter_klein: 'small stone guardian golem with a glowing blue core',
  stein_waechter: 'tall stone golem guardian blocking an ancient temple gate',
  echo_rufer: 'robed figure summoning glowing echo fragments from a dark portal',
  monolith_koloss: 'colossal stone monolith golem with glowing echo runes, night sky',
  steinhaut: 'ninja skin hardening into grey stone armor',
  erdbeben: 'ground shattering in a violent earthquake, dust clouds',
  versteinerung: 'ninja being petrified into grey stone from the feet up',
  steinschlag: 'boulders raining down and smashing hidden trap cards',
  monolith_erwachen: 'ancient stone monolith awakening with glowing eyes',
  steinmauer: 'stone wall erupting from the ground blocking an attack',
  felssturz: 'rockslide crashing down a steep cliff',
  echo_fluesterer: 'shadowy whispering figure made of dark mist, glowing mouth',
  stimmen_chor: 'choir of ghostly translucent figures singing in a dark cathedral',
  riss_fragment: 'floating dark crystal fragment radiating time energy',
  zeit_echo: 'ghostly echo of a ninja made of glowing clock particles',
  stimme_boss: 'ethereal dark entity made of swirling time energy and floating cards, galaxy rift behind',
  stimme_der_zeit: 'ghostly voice sound waves bending time around a frozen ninja',
  riss_welle: 'dark energy wave erasing playing cards from existence',
  zeit_sprung: 'ninja leaping through a glowing time portal',
  riss_duplikat: 'dark mirror duplicating a shadowy ninja figure',
  dunkle_prophezeiung: 'dark crystal ball showing an ominous prophecy, cards swirling around it',
  zeit_riss: 'glowing time rift tearing a spell card apart',
  echo_falle: 'echo portal deflecting an energy attack back to its source',
  zeit_blase: 'translucent time bubble freezing an attacking ninja mid-motion',
  echo_schattendoppel: 'dark shadowy double of a young ninja, inverted colors, glowing eyes',
  dunkler_genin: 'dark mirror version of a young genin ninja with a black chakra aura',
  spiegel_waechter: 'mirror-surfaced humanoid guardian reflecting the viewer',
  echo_naruto: 'dark evil version of a blonde whiskered ninja with black fox chakra cloak',
  echo_spiegel_boss: 'terrifying dark mirror entity, black silhouette of a ninja with glowing white eyes, mirror shards orbiting',
  spiegel_technik: 'mirror jutsu creating a dark reflection of a ninja',
  dunkles_rasengan: 'black swirling energy sphere with purple lightning',
  riss_oeffnung: 'massive dark rift opening in the night sky, cards flying into it',
  zeit_falte: 'time folding like paper over a frozen battlefield',
  spiegel_reflexion: 'giant mirror reflecting and shattering attacking ninjas',
  dunkler_zylinder: 'dark energy cylinder absorbing a bright attack',
  /* --- Zeitreise-Bogen (2026-07): Welle/Kiri/Sand/Sound/Pain/Akatsuki --- */
  mizuki_verraeter: 'sly white-haired chunin instructor ninja with an evil grin hurling a giant shuriken at night',
  fujin_raijin: 'two huge fat ogre-like ninja brothers with wild black hair roaring side by side, comical brutes',
  fuuma_shuriken: 'giant four-bladed windmill shuriken spinning through the air with motion blur',
  schriftrolle_siegelung: 'ancient ninja scroll unfurling with glowing kanji sealing script and chakra light',
  haku_eisnadel: 'graceful long-haired masked hunter ninja throwing glinting ice senbon needles',
  haku_spiegel: 'graceful ninja inside a dome of floating ice mirrors, many reflections, cold blue light',
  zabuza_momo: 'menacing bandage-faced ninja holding a huge executioner cleaver sword in thick mist',
  daemon_brueder: 'two masked ninja brothers linked by a spiked iron chain, metal claw gauntlets, ambush pose',
  mizu_token: 'translucent water clone of a ninja rising from a puddle, liquid surface',
  mizu_bunshin: 'ninja conjuring water clones that rise from a rippling water surface',
  senbon_sturm: 'deadly storm of silver senbon needles flying in formation, glinting',
  kirigakure_jutsu: 'hidden mist jutsu, dense white fog swallowing a battlefield with faint ninja silhouettes',
  makyou_hyoushou: 'dome of floating hexagonal ice mirrors, each reflecting a ninja, cold crystal light',
  eis_fesseln: 'chains and shackles of jagged ice freezing around a ninja limbs',
  gefrorene_falle: 'frozen trap of ice spikes erupting from the ground around a triggered kunai trap',
  zabuza_daemon: 'demon of the hidden mist, menacing silhouette with glowing eyes and giant cleaver in dense fog',
  haku_klinge: 'gentle but deadly long-haired ninja with senbon needles between fingers, loyal tool of the demon',
  oinin_jaeger: 'masked hunter-nin in a dark cloak with white porcelain mask, kirigakure insignia',
  kubikiribouchou: 'giant executioner cleaver sword with circle cutout stuck in the ground, mist swirling',
  suiro_jutsu: 'ninja trapped inside a perfect sphere of water held by an outstretched hand',
  lautloses_toeten: 'silent killing, assassin appearing behind a victim in thick mist, sword raised',
  yamata_no_jutsu: 'giant eight-headed white snake hydra emerging in a storm of dark chakra',
  fluchmal_kraft: 'black flame-like curse mark pattern spreading across a ninja neck, dark chakra aura',
  kusa_nagi: 'gleaming long katana blade extending from a giant snake mouth, kusanagi sword',
  shukaku: 'giant tanuki sand spirit with blue curse markings looming over a desert canyon, one tail',
  sabaku_sousou: 'sand burial, crushing wave of sand engulfing a trapped ninja',
  sand_token: 'small clone made of swirling sand forming a ninja shape',
  sand_klon: 'sand clone jutsu, ninja body made of sand dissolving and reforming',
  kisame_samehada: 'blue-skinned shark-like ninja grinning, holding a huge bandaged living sword',
  samehada: 'huge living sword unwrapped from bandages, covered in shark scales with a fanged mouth',
  kotoamatsukami: 'glowing hypnotic sharingan eye with swirling pattern and crows crossing a red moon',
  itachi_susanoo: 'giant spectral orange chakra warrior armor with ethereal blade surrounding a cloaked ninja',
  jirobo: 'huge fat red-haired ninja brute with earth chakra fists, sound four member',
  kidomaru: 'six-armed spider ninja with cursed markings aiming a golden bow, dark skin',
  tayuya: 'red-haired kunoichi playing a demonic flute, sound waves visible, curse markings',
  doki_token: 'giant ghostly ogre demon summoned by flute music, translucent and hulking',
  sakon_ukon: 'twin ninja brothers fused into one body, two heads back to back, dark curse marks',
  kimimaro_kaguya: 'pale white-haired ninja with sharp bones protruding from his arms and back, calm deadly face',
  spinnennetz: 'glistening golden spider web net snaring a ninja mid-leap',
  floeten_melodie: 'demonic flute melody conjuring ghostly demons from visible sound waves',
  knochen_tanz: 'ninja striking a deadly dance pose with white bone blades growing from his body',
  fingers_kugeln: 'hardened bone bullets firing from a ninja fingertips like bullets',
  fluchmal_stufe2: 'ninja transforming with curse mark level two, dark wings and horns, purple-black chakra',
  schall_barriere: 'visible sound wave barrier deflecting incoming kunai projectiles',
  pain_tendo: 'orange-haired ninja with ripple-pattern rinnegan eyes and facial piercings, akatsuki cloak, rain',
  chikushodo: 'rinnegan ninja summoning giant animals through glowing summoning seals, animal path',
  jumbo_hund_token: 'giant multi-headed chakra dog summon with spiked fur',
  ningendo: 'rinnegan ninja pulling a glowing human soul out of a body, human path',
  shurado: 'cyborg ninja with mechanical armor, extra arms and chakra cannons, asura path',
  gakido: 'rinnegan ninja absorbing a glowing chakra attack into a sealing shield, preta path',
  jigokudo: 'rinnegan ninja summoning the giant flaming head of the king of hell, naraka path',
  shinra_tensei: 'invisible repulsive force blast flattening the ground in a perfect ring around a ninja',
  chibaku_tensei: 'black gravity sphere pulling rocks and earth into a floating satellite moon',
  papier_sturm: 'storm of white paper sheets folding into deadly sharp shapes, paper angel jutsu',
  regen_der_erkenntnis: 'endless rain falling over a gloomy village, chakra-sensing glow in the drops',
  chou_shinra: 'cataclysmic almighty push blast destroying an entire village into a crater',
  madara_uchiha: 'legendary long spiky black-haired ninja in crimson armor with a war fan, sharingan eyes',
  obito_kamui: 'masked ninja with an orange spiral mask and one glowing sharingan, akatsuki cloak',
  zetsu: 'half black half white plant humanoid wrapped in a giant venus flytrap shell',
  weisser_zetsu: 'pale white plant humanoid clone with spiky flytrap ridges, blank eyes',
  gokka_mekkyaku: 'colossal sea of roaring fire covering a whole battlefield, majestic flame jutsu',
  tengai_shinsei: 'giant blazing meteor tearing through the clouds toward a battlefield',
  mugen_tsukuyomi: 'giant full moon with a rinnegan ripple pattern glowing red over a sleeping world',
  kamui_jutsu: 'spiral space-time vortex warping and sucking objects into another dimension',
  gedo_rinne_tensei: 'resurrection jutsu, glowing green life energy flowing back into a lying body',
  rinnegan_blick: 'close-up of a rinnegan eye with concentric ripple rings, purple glow',
  uchiwa_ruckstoss: 'ninja deflecting an attack with a large uchiha war fan, gust of wind reflecting it back',
  mokuton_falle: 'thick wooden vines and branches erupting from the ground trapping a ninja, wood style prison',
};

const ids = Object.keys(SUBJECTS).filter((id) => !fs.existsSync(path.join(ROOT, 'assets', 'cards', id + '.jpg')));
const start = parseInt(process.argv[2] || '0', 10);
fs.mkdirSync(RAW, { recursive: true });
let ok = 0, fail = [];
for (let i = start; i < ids.length; i++) {
  const id = ids[i];
  const out = path.join(RAW, id + '.png');
  if (fs.existsSync(out)) { ok++; continue; }
  const prompt = SUBJECTS[id] + STYLE;
  const r = spawnSync(process.execPath, [SERVER, '--prompt', prompt, '--out', out, '--aspect', '2:3', '--size', '1K'],
    { encoding: 'utf8', timeout: 120000 });
  const good = r.status === 0 && fs.existsSync(out) && fs.statSync(out).size > 30000;
  if (good) ok++;
  else { fail.push(id); console.log('FAIL ' + id + ' :: ' + String(r.stderr || r.stdout || '').slice(0, 160)); }
  if ((i + 1) % 10 === 0) console.log('--- ' + (i + 1 - start) + '/' + (ids.length - start) + ' (ok=' + ok + ', fail=' + fail.length + ')');
}
console.log('FERTIG: ok=' + ok + ' fail=' + fail.length + (fail.length ? ' :: ' + fail.join(',') : ''));
